<div class="container">
        <div class="wrapper">
          <div class="card">
            <div class="card-body">
      
              <div class="logoLink">
                <img class="logo" src="../assets/images/logo.svg" alt="" />
              </div>
      
              <div class="row">
                <div class="col">
                  <h2>Cadastro realizado com sucesso</h2>
                </div>
              </div>
      
              <div class="row">
                <div class="col">
                  <a href="/login" class="btn">Clique aqui para fazer login!</a>
                </div>
              </div>
      
            </div>
          </div>
        </div>
      </div>



    
  