

    <header>
      <a href="/" class="logoLink">
        <img class="logo" src="../assets/images/logo.svg" alt="GoLearn" />
      </a>
      <nav>
        <ul class="nav-links">
          <li><a href="/#about-us">Sobre</a></li>
          <li><a href="/#contact">Contato</a></li>
          <li><a href="/devs">Desenvolvedores</a></li>
        </ul>
      </nav>
      <nav>
        <a href="/login" class="login-btn">LOGIN</a>
        <a href="/signup" class="signup-btn">CRIAR CONTA</a>
      </nav>
    </header>
    <br><br>
    <section class="devs">
      <h1 class="title">CONHEÇA NOSSOS <span>DESENVOLVEDORES</span></h1>
      <div class="profile-wrapper">
        <div class="profile">
          <img src="../assets/profiles/leo.webp" alt="" />
          <h1>Leonardo <span>Cherri</span></h1>
          <div>
            <a href="https://github.com/LeoCherri" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a
              href="https://www.linkedin.com/in/leonardo-cherri-92a8102a2/"
              target="_blank"
            >
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>       

        <div class="profile">
          <img src="../assets/profiles/jorge.webp" alt="" />
          <h1>Jorge <span>Bernardi</span></h1>
          <div>
            <a href="https://github.com/Jorge-Bernardi" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a
              href="https://www.linkedin.com/in/jorgeguilhermebernardi/"
              target="_blank"
            >
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>
      

      
        <div class="profile">
          <img src="../assets/profiles/amanda.webp" alt="" />
          <h1>Amanda <span>Frolini</span></h1>
          <div>
            <a href="https://github.com/amandafrolini6" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a
              href="https://www.linkedin.com/in/amanda-frolini-097186301/"
              target="_blank"
            >
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>

        <div class="profile">
          <img src="../assets/profiles/regis.webp" alt="" />
          <h1>Felipe <span>Regiani</span></h1>
          <div>
            <a href="https://github.com/felipe-r-regiani" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a
              href="https://www.linkedin.com/in/felipe-regiani-0b377a307/"
              target="_blank"
            >
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>

        <div class="profile">
          <img src="../assets/profiles/junio.webp" alt="" />
          <h1>Junio <span>Matos</span></h1>
          <div>
            <a href="https://github.com/juniom237" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a href="https://www.linkedin.com/in/juniom237/" target="_blank">
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>

        <div class="profile">
          <img src="../assets/profiles/vitor.webp" alt="" />
          <h1>Vitor <span>Bressan</span></h1>
          <div>
            <a href="https://github.com/Bressanvt" target="_blank"
              ><i class="bx bxl-github"></i
            ></a>
            <a href="https://www.linkedin.com/in/bressanvt/" target="_blank">
              <i class="bx bxl-linkedin"></i>
            </a>
          </div>
        </div>
      </div>
    </section>

