<!-- CSS -->

<div class="container">
        <header>
            
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
               
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>
                            <?php echo $_SESSION['nome'] ?>
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">                        

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>        

    <h1>Gerenciar Usuários</h1>
    <table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Nível de Acesso</th>
            <th></th>
            <th></th>

        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->view->usuarios as $usuario): ?>
                <tr>
                    <td><?= $usuario['id'] ?></td>
                    <td><?= $usuario['nome'] ?></td>
                    <td><?= $usuario['email'] ?></td>
                    <td><?= $usuario['telefone'] ?></td>
                    <td><?= $usuario['nivel_acesso'] ?></td>
                    <td>
                        <form action="/admin/alterar_nivel" method="POST">
                            <input type="hidden" name="id_usuario" value="<?= $usuario['id'] ?>">
                            <select name="nivel_acesso">
                                <option value="1" <?= $usuario['nivel_acesso'] == 1 ? 'selected' : '' ?>>Administrador</option>
                                <option value="2" <?= $usuario['nivel_acesso'] == 2 ? 'selected' : '' ?>>Gestor</option>
                                <option value="3" <?= $usuario['nivel_acesso'] == 3 ? 'selected' : '' ?>>Usuario</option>
                            </select>
                            <button class"button-alterar" type="submit">Alterar</button>
                        </form>
                    </td>
                </tr>
                <?php endforeach; ?>
        </tbody>
    </table>
</table>


