
    <div id="page" class="flex">
      <div>
        <a href="/"
          ><img src="../assets/images/logo.svg" alt=""
        /></a>
        <main class="main-login">
          <div class="headline"><h1>Recuperação de conta</h1></div>
          <p>
            Insira o código enviado em seu e-mail para recuperar o acesso a
            conta
          </p>
          <form action="/password-change">
            <div class="input-wrapper">
              <label for="code">Código</label>
              <input
                id="code"
                type="number"
                name="code"
                placeholder="Insira o código enviado no seu e-mail"
                required
              />
            </div>

            <button type="submit">Enviar</button>
          </form>
        </main>
      </div>
      <img src="../assets/images/banner.svg" alt="" />
    </div>
  </body>
</html>
