
    <header>
      <a href="/" class="logoLink">
        <img class="logo" src="assets/images/logo.svg" alt="GoLearn" />
      </a>
      <nav>
        <ul class="nav-links">
          <li><a href="#about-us">Sobre</a></li>
          <li><a href="#contact">Contato</a></li>
          <li><a href="/devs">Desenvolvedores</a></li>
        </ul>
      </nav>
      <nav>
        <a href="/login" class="login-btn">LOGIN</a>
        <a href="/signup" class="signup-btn">CRIAR CONTA</a>
      </nav>
    </header>
    <br><br>
    <section class="home" id="home">
      <div class="home-text">
        <h2 class="title">
          CONCENTRE-SE NO <span>APRENDIZADO</span>,<br />
          A<span> ORGANIZAÇÃO</span> É POR NOSSA CONTA!
        </h2>
        <p>
          Adeus à bagunça e à complexidade das plataformas convencionais das Big
          Techs.<br />
          Com a GoLearn, organização é a palavra-chave.
        </p>
        <a href="#about-us" class="about-btn">SAIBA MAIS</a>
        <a href="/signup" class="meet-btn">CONHEÇA A PLATAFORMA</a>
      </div>
      <div class="home-img">
        <img src="assets/images/mockup.svg" alt="" />
      </div>
    </section>

    <section class="about-us" id="about-us">
      <div class="about-text">
        <h2 class="title">SOBRE <span>NÓS</span></h2>
        <p>
          A <span>GoLearn</span> é uma plataforma de estudos inovadora projetada
          para proporcionar
          <span>organização, praticidade e eficiência</span> aos alunos e
          professores. Ao se registrar como aluno de uma instituição, os
          usuários têm acesso a todo o conteúdo compartilhado por seus colegas e
          professores. Nossa plataforma apresenta uma interface
          <span>intuitiva</span>, com ícones que direcionam para materiais,
          vídeo aulas, listas de tarefas e atividades extras. Todos os conteúdos
          são submetidos a uma verificação para garantir sua
          <span>qualidade e relevância</span>. Com a GoLearn, estudar e
          colaborar nunca foi tão <span>simples e eficaz</span>.
        </p>
        <a href="/signup" class="meet-btn">CONHEÇA A PLATAFORMA</a>
      </div>
      <div class="about-img">
        <img src="assets/images/about.svg" alt="" />
      </div>
    </section>

    <section class="for-teacher">
      <div class="teacher-text">
        <h2 class="title">PARA <span>PROFESSORES</span></h2>
        <p>
          A <span>GoLearn</span> não é apenas para estudantes buscando
          organização; é uma ferramenta
          <span>revolucionária para professores</span> que desejam levar seu
          ensino para o próximo nível. Com a nossa plataforma
          <span>intuitiva</span>, você terá acesso a uma gama de recursos,
          projetados para otimizar seu tempo e aprimorar a experiência de
          aprendizado dos seus alunos.
        </p>
        <a href="/signup" class="meet-btn">CONHEÇA A PLATAFORMA</a>
      </div>
      <div class="teacher-img">
        <img src="assets/images/teacher.svg" alt="" />
      </div>
    </section>

    <section class="contact" id="contact">
      <div class="contact-text">
        <h2 class="title">ENTRE EM <span>CONTATO</span></h2>
        <p>
          Entre em contato conosco para sanar dúvidas, discutir interesses e
          oportunidades de parceria. Estamos abertos para sugestões ou apenas
          para ter uma conversa.
        </p>
        <div class="social-icons">
          <a href="#" class="socialIcon"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="socialIcon"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="socialIcon"><i class="bx bxl-instagram"></i></a>
          <a href="#" class="socialIcon"><i class="bx bxl-linkedin"></i></a>
          <a href="#" class="socialIcon"><i class="bx bxl-github"></i></a>
        </div>
      </div>
      <form action="" class="contact-form">
        <div class="input-wrapper">
          <label for="nome">Nome completo</label>
          <input
            id="nome"
            type="text"
            name="nome"
            placeholder="Digite seu nome completo"
          />
        </div>
        <div class="input-wrapper">
          <div class="label-wrapper">
            <label for="email">E-mail</label>
          </div>
          <input
            id="email"
            type="email"
            name="email"
            placeholder="Digite seu email"
          />
        </div>
        <div class="input-wrapper">
          <div class="label-wrapper">
            <label for="telefone">Telefone</label>
          </div>
          <input
            id="telefone"
            type="tel"
            name="telefone"
            placeholder="Digite seu telefone"
          />
        </div>
        <div class="input-wrapper">
          <div class="label-wrapper">
            <label for="textarea">Mensagem</label>
          </div>
          <textarea
            name="textarea"
            id="textarea"
            placeholder="Escreva sua mensagem"
            maxlength="500"
            oninput="counter()"
            onfocus="showCounter()"
            onblur="hideCounter()"
          ></textarea>
          <div id="contador"></div>
        </div>
        <button type="submit">Enviar</button>
      </form>
    </section>

    <footer>
      
      <div>
        <p>
          A GoLearn é uma plataforma de estudos que preza pela organização e a
          eficiência do aprendizado de seus usuários, sejam alunos ou
          professores.
        </p>
      </div>
      
    </footer>
    <div class="copy">
      <h3>© 2024 GoLearn | Todos os direitos reservados</h3>
    </div>

