
    <div id="page" class="flex">
      <div>
        <a href="/"
          ><img src="../assets/images/logo.svg" alt=""
        /></a>
        <main class="main-login">
          <div class="headline"><h1>Recuperação de conta</h1></div>
          <p>Redefina sua senha para recuperar o acesso a conta</p>
          <form action="/login">
            <div class="input-wrapper">
              <div class="label-wrapper">
                <label for="senha">Nova senha</label>
              </div>
              <input
                id="senha"
                type="password"
                name="senha"
                min="8"
                max="16"
                placeholder="Digite sua nova senha"
                required
              />
              <i
                onclick="togglePassword()"
                class="eye show show-password bx bx-show"
              ></i>
              <i
                onclick="togglePassword()"
                id="hide"
                class="eye hide hide-password bx bx-hide"
              ></i>
            </div>

            <button type="submit">Redefinir</button>

            <div class="create-account">
              <p>Não possui uma conta? <a href="/signup">Cadastre-se</a></p>
            </div>
          </form>
        </main>
      </div>
      <img src="../assets/images/banner.svg" alt="" />
    </div>

    <script src="../js/script.js"></script>
  </body>
</html>
