
    <div id="page" class="flex">
      <div>
        <a href="/"
          ><img src="../assets/images/logo.svg" alt=""
        /></a>
        <main class="main-login">
          <div class="headline"><h1>Recuperação de conta</h1></div>
          <p>
            Coloque seu email abaixo e iremos enviar um código de redefinição de
            senha
          </p>
          <form action="/code">
            <div class="input-wrapper">
              <label for="email">E-mail</label>
              <input
                id="email"
                type="email"
                name="email"
                placeholder="Digite seu e-mail"
                required
              />
            </div>

            <button type="submit">Enviar</button>

            <div class="create-account">
              <p>Não possui uma conta? <a href="/signup">Cadastre-se</a></p>
            </div>
          </form>
        </main>
      </div>
      <img src="../assets/images/banner.svg" alt="" />
    </div>

