<?php
if (!isset($_SESSION)) {
    
    session_start();
}

$limite = 10; // Define o número máximo de livros a exibir
$contador = 0;

?>
<div class="container">
        <header>
            <button class="menu-button" id="menuButton" onclick="toggleSidebar()">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </button>
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
                
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>
                            <?php echo $_SESSION['nome'] ?>
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">
                        <li class="profile-dropdown-list-item">
                            <a href="/perfil">
                                <i class="fa-regular fa-user"></i>
                                Edit Profile
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-envelope"></i>
                                Inbox
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-chart-line"></i>
                                Analytics
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-sliders"></i>
                                Settings
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-circle-question"></i>
                                Help & Support
                            </a>
                        </li>
                        <hr />

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>

        <aside class="sidebar" id="sidebar">
            <nav class="menu">
                <ul>
                    <li>
                        <a href="/apphome">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/book">
                            <i class="fa-solid fa-book"></i>
                            Livros
                        </a>
                    </li>
                    <li>
                        <a href=" /upload">
                            <i class="fa-solid fa-upload"></i>
                            Uplod
                        </a>
                    </li>
                    <li>
                        <a href="/calendario">
                            <i class="fa-regular fa-calendar-days"></i>
                            Calendario
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main id="mainContent">
        <div class="container">
        <h2 class="titulo">Pesquisar Livro</h2>
    <form action="/buscar" method="get" class="pesquisa">
        <input type="text" name="termo" placeholder="Digite o nome do livro" value="<?= $_GET['termo'] ?? '' ?>">
        <button type="submit" class="serarch-button">
            <i class="fa-solid fa-search"></i>
        </button>
    </form>   

   
        <div class="livros">
            <?php 
            if(isset($this->view->livros ))
            {

            
            foreach ($this->view->livros as $livro): ?>
                <div class="livro">
                    <h2><?= $livro['titulo'] ?></h2>
                    <p><strong>Autor:</strong> <?= $livro['autor'] ?></p>
                    <?php if ($livro['capa']): ?>
                        <img src="<?= $livro['capa'] ?>" alt="Capa do Livro">
                    <?php else: ?>
                        <p>Sem imagem disponível</p>
                    <?php endif; ?>
                </div>
            <?php endforeach;} ?>
        </div>
  
</div>


</main>
</div>