
    <div class="container">
        <header>
            <button class="menu-button" id="menuButton" onclick="toggleSidebar()">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </button>
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
                <div>
                    <button class="serarch-button">
                        <i class="fa-solid fa-search"></i>
                    </button>

                </div>
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>Victoria
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">
                        <li class="profile-dropdown-list-item">
                            <a href="/perfil">
                                <i class="fa-regular fa-user"></i>
                                Edit Profile
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-envelope"></i>
                                Inbox
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-chart-line"></i>
                                Analytics
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-sliders"></i>
                                Settings
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-circle-question"></i>
                                Help & Support
                            </a>
                        </li>
                        <hr />

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>

        <aside class="sidebar" id="sidebar">
            <nav class="menu">
                <ul>
                    <li>
                        <a href="/apphome">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/book">
                            <i class="fa-solid fa-book"></i>
                            Livros
                        </a>
                    </li>
                    <li>
                        <a href=" /uplod">
                            <i class="fa-solid fa-upload"></i>
                            Uplod
                        </a>
                    </li>
                    <li>
                        <a href="/calendario">
                            <i class="fa-regular fa-calendar-days"></i>
                            Calendario
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main id="mainContent">
            <h2 class="titulo">Pesquisar Livro</h2>
            <form action="" method="get" class="pesquisa">
                <input type="text" placeholder="Pesquisar Livros">
                <button type="submit" class="serarch-button">
                    <i class="fa-solid fa-search"></i>
                </button>
            </form>

            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Autor</th>
                        <th>Editora</th>
                        <th>Edição</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </main>
    </div>
