<?php
if (!isset($_SESSION)) {
    
    session_start();
}
?>
<div class="container">
        <header>
            <button class="menu-button" id="menuButton" onclick="toggleSidebar()">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </button>
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
               
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>
                            <?php echo $_SESSION['nome'] ?>
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">
                        <li class="profile-dropdown-list-item">
                            <a href="/perfil">
                                <i class="fa-regular fa-user"></i>
                                Edit Profile
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-envelope"></i>
                                Inbox
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-chart-line"></i>
                                Analytics
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-sliders"></i>
                                Settings
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-circle-question"></i>
                                Help & Support
                            </a>
                        </li>
                        <hr />

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>

        <aside class="sidebar" id="sidebar">
            <nav class="menu">
                <ul>
                    <li>
                        <a href="/apphome">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/book">
                            <i class="fa-solid fa-book"></i>
                            Livros
                        </a>
                    </li>
                    <li>
                        <a href=" /upload">
                            <i class="fa-solid fa-upload"></i>
                            Uplod
                        </a>
                    </li>
                    <li>
                        <a href="/calendario">
                            <i class="fa-regular fa-calendar-days"></i>
                            Calendario
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main id="mainContent">
        <div class="main-arquivo">
                <h1>Arquivos para Estudos</h1>
                
                <table class="table-arquivo">
                    <thead >
                        <tr>
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Tamanho</th>
                            <th>Enviado Por</th>
                            <th>Data de Envio</th>
                            <th>Ações</th>
                            
                        </tr>
                    </thead>
                    <?php
                                    
                    ?>
                    <tbody>
                    
                         <?php foreach ($this->view->arquivo as $arquivos): ?>
                            <tr>
                           
                                <td><?= htmlspecialchars($arquivos['nome_arquivo']) ?></td>
                                <td><?= htmlspecialchars($arquivos['tipo_arquivo']) ?></td>
                                <td><?= htmlspecialchars($arquivos['tamanho_arquivo']) ?> KB</td>
                                <td><?= htmlspecialchars($arquivos['enviado_por']) ?></td>
                                <td><?= htmlspecialchars($arquivos['data_envio'] ) ?></td>
                                <td><a class"btn-download" href="<?= htmlspecialchars($arquivos['caminho_arquivo']) ?>" download>Baixar</a></td>
                            </tr>
                        <?php endforeach; ?>
                
                    </tbody>
                </table>
                
                
            </div>
            


        </main>
    </div>
