
    <div class="container">
        <header>
            <button class="menu-button" id="menuButton" onclick="toggleSidebar()">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </button>
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
                
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>
                            <?php echo $_SESSION['nome'] ?>
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">
                        <li class="profile-dropdown-list-item">
                            <a href="/perfil">
                                <i class="fa-regular fa-user"></i>
                                Edit Profile
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-envelope"></i>
                                Inbox
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-chart-line"></i>
                                Analytics
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-sliders"></i>
                                Settings
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-circle-question"></i>
                                Help & Support
                            </a>
                        </li>
                        <hr />

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>

        <aside class="sidebar" id="sidebar">
            <nav class="menu">
                <ul>
                    <li>
                        <a href="/apphome">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/book">
                            <i class="fa-solid fa-book"></i>
                            Livros
                        </a>
                    </li>
                    <li>
                        <a href=" /upload">
                            <i class="fa-solid fa-upload"></i>
                            Uplod
                        </a>
                    </li>
                    <li>
                        <a href="/calendario">
                            <i class="fa-regular fa-calendar-days"></i>
                            Calendario
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main id="mainContent">
        <div class="main-uplod">
        

        

        <div id="container">

        <?php if (isset($_SESSION['mensagem'])): ?>
            <div class="alert">
                <?= $_SESSION['mensagem']; ?>
                <?php unset($_SESSION['mensagem']); ?>
            </div>
        <?php endif; ?>
            <div class="tab-buttons">
                <button class="tab-btn active" onclick="showForm('form1')">
                    Uploads Videos
                </button>

                <button class="tab-btn" onclick="showForm('form2')">
                    Uploads Arquivos
                </button>
                <button class="tab-btn" onclick="showForm('form3')">
                    Criar playlists
                </button>
                <button class="tab-btn" onclick="showForm('form4')">
                    Adicionar video na Playlist
                </button>             
            </div>

            <div class="tab-contents">
            <div class="content" id="form4">
            
                    <form action="/playlist/adicionar_video" method="POST">
                        <label for="id_playlist">Playlist:</label>
                        <select name="id_playlist" id="id_playlist" required>
                            <option value="">Escolha uma playlist</option>                            
                                <?php foreach ($this->view->playlists as $playlists): ?>
                                    <option value="<?= htmlspecialchars($playlists['id']) ?>">
                                        <?= htmlspecialchars($playlists['titulo']) ?>
                                    </option>
                                <?php endforeach; ?> 
                        </select>

                        <label for="id_video">Selecione um vídeo:</label><br>
                        <select name="id_video" id="id_video" required>
                            <option value="">Escolha um vídeo</option>
                                <?php foreach ($this->view->video as $videos): ?>
                                    <option value="<?= htmlspecialchars($videos['id']) ?>">
                                        <?= htmlspecialchars($videos['titulo']) ?>
                                    </option>
                                <?php endforeach; ?>
                        </select>

                        <button type="submit">Adicionar Vídeo</button>
                    </form>
                </div>


                <div class="content" id="form3">
                    <form action="/playlist/salvar" method="POST">
                        <label for="titulo">Título da Playlist:</label><br>
                        <input type="text" name="titulo" id="titulo" placeholder="Digite o título da playlist"required>
                        <label for="descricao">Descrição:</label><br>
                        <textarea name="descricao" id="descricao" rows="4" placeholder="Digite uma descrição para a playlist"></textarea>               
                        <button type="submit">Criar Playlist</button>
                    </form>
                </div>
             
                <div class="content" id="form2">
                    <form action="/arquivo/salvar" method="POST" enctype="multipart/form-data">
                        <div>
                            <label for="arquivo">Escolha o arquivo:</label>
                            <input type="file" id="arquivo" name="arquivo" required>
                        </div>              
                        <button type="submit">Enviar</button>                    
                    </form>
                </div>
                
                <div class="content active" id="form1">
                    <form action="/videoaula/salvar" method="POST" enctype="multipart/form-data">
                    <label for="titulo">Título do Vídeo:</label>
                    <input type="text" name="titulo" id="titulo" required>
                    <label for="descricao">Descrição:</label>
                    <textarea name="descricao" id="descricao"></textarea>
                    <label for="video">Selecione o Vídeo:</label>
                    <input type="file" name="video" id="video" accept="video/*" required>
                    <button type="submit">Enviar Vídeo</button>                    
                    </form>
                </div> 
            </div>
        </div>
        </main>
    </div>
