<?php
if (!isset($_SESSION)) {
    
    session_start();
}
?>
<head>
    <title><?= htmlspecialchars($this->view->playlist['titulo']) ?></title>
</head>
    <div class="container">
        <header>
            <button class="menu-button" id="menuButton" onclick="toggleSidebar()">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </button>
            <div class="logo">
                <img src="/assets/images/logo.svg" alt="logo">
            </div>
            <div class="button">
                
                <div class="profile-dropdown">
                    <div onclick="initializeDropdown()" class="profile-dropdown-btn">
                        <div class="profile-img">
                            <i class="fa-solid fa-circle "></i>
                        </div>

                        <span>
                            <?php echo $_SESSION['nome'] ?>
                            <i class="fa-solid fa-angle-down"></i>
                        </span>
                    </div>

                    <ul class="profile-dropdown-list">
                        <li class="profile-dropdown-list-item">
                            <a href="/perfil">
                                <i class="fa-regular fa-user"></i>
                                Edit Profile
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-envelope"></i>
                                Inbox
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-chart-line"></i>
                                Analytics
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-solid fa-sliders"></i>
                                Settings
                            </a>
                        </li>

                        <li class="profile-dropdown-list-item">
                            <a href="#">
                                <i class="fa-regular fa-circle-question"></i>
                                Help & Support
                            </a>
                        </li>
                        <hr />

                        <li class="profile-dropdown-list-item">
                            <a href="/sair">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>


        </header>

        <aside class="sidebar" id="sidebar">
            <nav class="menu">
                <ul>
                    <li>
                        <a href="/apphome">
                            <i class="fa-solid fa-house"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/book">
                            <i class="fa-solid fa-book"></i>
                            Livros
                        </a>
                    </li>
                    <li>
                        <a href=" /upload">
                            <i class="fa-solid fa-upload"></i>
                            Uplod
                        </a>
                    </li>
                    <li>
                        <a href="/calendario">
                            <i class="fa-regular fa-calendar-days"></i>
                            Calendario
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <main id="mainContent">
        <a class="btn" href="/playlists">Voltar para Playlists</a>
        <h1><?= htmlspecialchars($this->view->playlist['titulo']) ?></h1>
        
        

        <?php if (isset($_SESSION['mensagem'])): ?>
            <div class="alert">
                <?= $_SESSION['mensagem']; ?>
                <?php unset($_SESSION['mensagem']); ?>
            </div>
        <?php endif; ?>

        <?php if (!empty($this->view->videos)): ?>
            <ul>
                <?php foreach ($this->view->videos as $video): ?>
                    <li>
                        <h3><?= htmlspecialchars($video['titulo']) ?></h3>
                        <video width="320" height="240" controls>
                            <source src="/<?= htmlspecialchars($video['caminho']) ?>" type="video/mp4">
                            Seu navegador não suporta o elemento de vídeo.
                        </video>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p>Esta playlist ainda não possui vídeos.</p>
        <?php endif; ?>


        </main>
    </div>
