<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!-- METATAGS -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"   rel="stylesheet" />

	<link  rel="shortcut icon" type="image/png" href="/assets/images/favicon.svg" />

	<!-- CSS -->
	<link rel="stylesheet" href="/css/index1.css">

	<!-- SCRIPTS -->
	
	<!-- TITTLE -->
	<title>GoLearn </title>
</head>
<body>
	
<?php $this->content() ?>
</body>
</html>
