<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!-- METATAGS -->
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"   rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"
	/>
	<!--icone-->
	<link  rel="shortcut icon" type="image/png" href="/assets/images/favicon.svg" />

	<!-- CSS -->
	<link rel="stylesheet" href="/css/index.css">

	<!-- SCRIPTS -->
	<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>
	<script src="/javascript/script2.js"></script>
	
	
	<!-- TITTLE -->
	<title>GoLearn </title>
</head>
<body>

    
   
	
<?php $this->content() ?>
</body>
</html>
